### ISSUE TITLE
Add note about the loggerFactory property in your controller

### ISSUE THREAD

**Issue by weaverryan** [knpuniversity/drupal-under-the-hood#3]
When we create the `$loggerFactory` property in this video: https://knpuniversity.com/screencast/drupal8-under-the-hood/get-service-from-container#fetch-another-service-a-logger, we need to add this note (I don't know the exact second it needs to be added, at this moment!)

> In Drupal 8.1, name your property something different - like `loggerFactoryService`. The
> reason is that `ControllerBase` _now_ allows you to access the logger without needing
> dependency injection. This exercise is still totally valid for learning, but you'll need to
> rename the property to avoid conflicting with the property in `ControllerBase`.

**Comment by Leannapelham** [comment]
Added to video - exporting now and I'll send it along to our Drupalize.me friends
